const restaurants = [
  {
    name: "南蛮子（进贤路店）",
    name_en: "Nán Mán Zǐ (Jinxian Rd)",
    category: "yunguizhou",
    category_en: "yunguizhou",
    neighborhood: "法租界 · 浦西核心区",
    neighborhood_en: "French Concession · Puxi",
    address: "徐汇·进贤路",
    address_en: "Xuhui · Jinxian Rd (French Concession)",
    description: "火龙果心中第一名！2026年度回国的第一顿必须安排在这里！云南菜馆，藏在法租界的街边小店。环境正常偏简朴，明厨亮灶，隔着玻璃能直接看见后厨操作，锅气拉满。更适合朋友聚餐而非正式请客。没有包间，但楼上有大圆桌，2到10个人都能坐得舒服。",
    description_en: "火龙果's #1 in Shanghai — the first meal of every homecoming, no exceptions! A no-frills Yunnan spot in the French Concession. Lively open kitchen — you can watch the wok action through the glass. Better for friends than formal hosting. No private rooms, but upstairs has a big round table for 2–10.",
    mustTry: ["黑三剁", "木姜子牛肉", "菌子鸡汤", "炸排骨", "烤罗非鱼", "酥红豆", "辣子鸡", "牙签牛肉"],
    mustTry_en: ["Black Three-Mince (黑三剁)", "Litsea Beef (木姜子牛肉)", "Wild Mushroom Chicken Soup (菌子鸡汤)", "Fried Pork Ribs (炸排骨)", "Grilled Tilapia (烤罗非鱼)", "Crispy Red Beans (酥红豆)", "Chilli Chicken (辣子鸡)", "Toothpick Beef (牙签牛肉)"],
    priceRange: "¥¥",
    perPerson: "人均 ¥100",
    perPerson_en: "~¥100 / person",
    reservation: "平时无需预定，周末饭点可在大众点评提前订位",
    reservation_en: "Walk-ins welcome on weekdays. For weekend peak hours, book ahead on Dianping.",
    groupSize: ["2–6人", "6人以上"],
    occasion: ["朋友聚餐"],
    atmosphere: ["简单", "热闹"],
    emoji: "🌿",
    rating: 3,
    spicy: 1,
    dianping: "https://m.dianping.com/shop/2201962"
  },
  {
    name: "野果与山椒",
    name_en: "Yěguǒ & Shānjiāo",
    category: "yunguizhou",
    category_en: "yunguizhou",
    neighborhood: "静安区 · 浦西",
    neighborhood_en: "Jing'an · Puxi",
    address: "静安·富民路 / 长寿路",
    address_en: "Jing'an · Fumin Rd / Changshou Rd",
    description: "贵阳老板开的正宗贵州菜，菜单设计很用心，经常按季节更新。强烈建议直接点菜吃，不要点酸汤火锅，菜比火锅好吃太多。这家的鸡尾酒调得也很好，有些独特小巧思！最好提前订位。没有包厢，环境热闹。更适合朋友聚餐，不适合请客吃饭。",
    description_en: "Authentic Guizhou cuisine by a Guiyang chef, with a thoughtfully designed menu that changes seasonally. Order à la carte — the dishes are far better than the sour-broth hotpot. The cocktails are surprisingly well-crafted with some creative twists. Book ahead. No private rooms, lively atmosphere. Better for friends than formal hosting.",
    mustTry: ["宫爆板筋", "铁签烤肉", "牛肉青菜锅", "辣子鸡", "脆哨土豆", "水豆豉茼蒿", "豆腐圆子", "洋芋粑"],
    mustTry_en: ["Kung Pao Tendon (宫爆板筋)", "Skewer Grilled Meat (铁签烤肉)", "Beef & Greens Pot (牛肉青菜锅)", "Chilli Chicken (辣子鸡)", "Crispy Lard Potato (脆哨土豆)", "Fermented Soybean Chrysanthemum (水豆豉茼蒿)", "Tofu Balls (豆腐圆子)", "Potato Cake (洋芋粑)"],
    priceRange: "¥¥",
    perPerson: "人均 ¥120",
    perPerson_en: "~¥120 / person",
    reservation: "强烈建议提前在大众点评订位",
    reservation_en: "Reservations strongly recommended — book ahead on Dianping.",
    groupSize: ["2–6人"],
    occasion: ["朋友聚餐"],
    atmosphere: ["热闹", "精致"],
    rating: 2,
    spicy: 2,
    dianpingLinks: [
      { url: "https://m.dianping.com/shop/731796035", label: "大众点评（富民路店）", label_en: "Dianping (Fumin Rd)" },
      { url: "https://m.dianping.com/shop/1846224196", label: "大众点评（长寿路店）", label_en: "Dianping (Changshou Rd)" },
    ],
  },
  {
    name: "卿家姆",
    name_en: "Qīng Jiā Mǔ",
    category: "jiangzhe",
    category_en: "jiangzhe",
    neighborhood: "全市多家门店",
    neighborhood_en: "Multiple locations across Shanghai",
    address: "全市多区（外滩店推荐）",
    address_en: "Multiple locations (Bund branch recommended)",
    description: "从宁波开来上海的江浙小海鲜馆子，精致而不做作。外滩店位置很好，但大厅无法订位，周末可能需要等位；包间可订但低消离谱，不建议。适合朋友聚餐或小规模请客，不适合家庭大桌。",
    description_en: "A Ningbo-origin Jiangzhe seafood restaurant, refined without being stuffy. The Bund branch has a great location — no reservations for the main hall (expect a wait on weekends), and private rooms have an unreasonable minimum spend. Best for friends or intimate hosting, not large family gatherings.",
    mustTry: ["熟醉大头虾", "小馆红烧肉", "爆炒黄牛肉", "腐竹黄鱼卷", "熟醉大闸蟹", "葱油东海小馆"],
    mustTry_en: ["Drunken Prawns (熟醉大头虾)", "Braised Pork — not sweet! (小馆红烧肉)", "Stir-fried Yellow Beef (爆炒黄牛肉)", "Tofu Skin & Yellow Croaker Roll (腐竹黄鱼卷)", "Drunken Hairy Crab (熟醉大闸蟹)", "Scallion Oil East Sea Catch (葱油东海小馆)"],
    priceRange: "¥¥¥",
    perPerson: "人均 ¥150–200",
    perPerson_en: "~¥150–200 / person",
    reservation: "大厅不可订位；包间可订但低消极高，不建议",
    reservation_en: "No reservations for main hall; private rooms available but minimum spend is excessive — not recommended.",
    groupSize: ["2–6人"],
    occasion: ["朋友聚餐", "可以请客"],
    atmosphere: ["精致"],
    rating: 2,
    dianpingLinks: [
      { url: "https://m.dianping.com/shop/1022572955", label: "大众点评（外滩店）", label_en: "Dianping (Bund)" },
      { url: "https://m.dianping.com/shop/877017586", label: "大众点评（中山公园店）", label_en: "Dianping (Zhongshan Park)" },
    ],
  },
  {
    name: "山石榴",
    name_en: "Shān Shí Liú",
    category: "yunguizhou",
    category_en: "yunguizhou",
    neighborhood: "全市多家门店",
    neighborhood_en: "Multiple locations across Shanghai",
    address: "全市多区",
    address_en: "Multiple locations citywide",
    description: "全上海最标准化的贵州菜，出品稳定不踩雷，包含所有经典菜色，适合一站式体验正宗贵州菜。花溪牛肉粉超适合一人食，中午去吃一碗美滋滋。个人认为酸汤鱼做得一般，但很受大众欢迎。不能订座，只能现场排队，建议早去或错峰；可外卖，味道和堂食基本一致。无包厢，环境偏热闹。更适合朋友聚餐，不适合请客吃饭。",
    description_en: "The most consistent Guizhou chain in Shanghai — reliable across the board, covers all the classics. Great for a one-stop intro to Guizhou cuisine. The Huaxi beef noodles are a perfect solo lunch. The sour fish soup is popular but unremarkable in 火龙果's view. No reservations — queue in person, go early or off-peak. Delivery holds up well. No private rooms, lively vibe. Better for friends than formal hosting.",
    mustTry: ["宫爆板筋", "雷家豆腐圆子", "辣子鸡", "糟辣小炒肉", "铁签烤肉", "水豆豉炒蓬蒿菜", "花溪牛肉粉（一人食首选）"],
    mustTry_en: ["Kung Pao Tendon (宫爆板筋)", "Leijia Tofu Balls (雷家豆腐圆子)", "Chilli Chicken (辣子鸡)", "Pickled Chilli Stir-fry (糟辣小炒肉)", "Skewer Grilled Meat (铁签烤肉)", "Fermented Soybean Chrysanthemum (水豆豉炒蓬蒿菜)", "Huaxi Beef Noodles — perfect solo (花溪牛肉粉)"],
    priceRange: "¥¥",
    perPerson: "人均 ¥100–150",
    perPerson_en: "~¥100–150 / person",
    groupSize: ["一人可行", "2–6人"],
    occasion: ["朋友聚餐"],
    atmosphere: ["热闹", "精致"],
    rating: 1,
    spicy: 2,
    dianpingLinks: [
      { url: "https://m.dianping.com/shopinfo/G9WTLikdO9Rtriua", label: "大众点评（K11店）", label_en: "Dianping (K11 Mall)" },
      { url: "https://m.dianping.com/shopinfo/H3tsUJ3AA6GA6mo8", label: "大众点评（西岸梦中心店）", label_en: "Dianping (West Bund Dream Centre)" },
    ],
  },
  {
    name: "清晨落夜小酒馆",
    name_en: "Qīngchén Luòyè Xiǎojiǔguǎn",
    category: "jiangxi",
    category_en: "jiangxi",
    neighborhood: "静安寺 · 静安区",
    neighborhood_en: "Jing'an Temple · Jing'an District",
    address: "静安·静安寺",
    address_en: "Jing'an · Jing'an Temple",
    description: "偏爆炒的江西菜，聚集江西各地方的特色，属于集大成的一家。环境简单，饭点可能要排队，建议错峰前往。",
    mustTry: ["麻辣鸡爪", "鱼干辣椒炒肉", "莲花血鸭"],
    groupSize: ["2–6人"],
    occasion: ["朋友聚餐"],
    atmosphere: ["简单", "热闹"],
    perPerson: "人均 ¥100–150",
    perPerson_en: "~¥100–150 / person",
    rating: 1,
    spicy: 5,
    dianping: "https://m.dianping.com/shop/1804042946",
  },
  {
    name: "炙苑",
    name_en: "Zhì Yuàn",
    category: "japanese",
    category_en: "japanese",
    neighborhood: "浦东 · 世纪公园板块",
    neighborhood_en: "Pudong · Century Park",
    address: "浦东·世纪公园",
    address_en: "Pudong · Century Park",
    description: "日式烧肉天花板，没有并列的。什么肉都好吃，可以根据人数和喜好点拼盘，反正点下来都差不多贵。碾压铁屋、老干杯、橘炎胡同等一众高端日式烧肉。人均500不含酒已经能吃得非常满足。",
    description_en: "The undisputed peak of Japanese yakiniku in Shanghai — nothing comes close. Every cut is exceptional; order a combo platter sized to your group. Leaves Iron House, Don Quijote, and every other high-end yakiniku in the dust. ¥500/person ex-drinks is more than satisfying.",
    mustTry: ["拼盘（按人数点）", "和牛海胆塔塔", "海胆和牛釜饭"],
    mustTry_en: ["Combo Platter (sized to group)", "Wagyu & Uni Tartare (和牛海胆塔塔)", "Uni Wagyu Kamameshi (海胆和牛釜饭)"],
    priceRange: "¥¥¥¥",
    perPerson: "人均 ¥500（不含酒）",
    perPerson_en: "~¥500 / person (ex-drinks)",
    reservation: "可提前订位，有包间",
    reservation_en: "Reservations available; private rooms offered.",
    groupSize: ["2–6人", "有包间"],
    occasion: ["朋友聚餐", "可以请客"],
    atmosphere: ["精致"],
    rating: 3,
    dianping: "https://www.dianping.com/shop/H3pRXBQ0J4tT09I2",
  },
  {
    name: "鮨小野",
    name_en: "Sushi Ono",
    category: "japanese",
    category_en: "japanese",
    neighborhood: "世纪公园 / 前滩（两家均可）",
    neighborhood_en: "Century Park / Qiantan (both branches)",
    address: "浦东·世纪公园 / 前滩",
    address_en: "Pudong · Century Park / Qiantan",
    description: "板前寿司，可以自己点单——千万不要点套餐，直接点你想吃的，每一样都极度新鲜！火龙果力推：比很多人均1k+的日料还新鲜还好吃，性价比和味道全部拉满。因为只有板前，人多了坐一排会根本听不到彼此说话，2-3人最适合。必须提前大众点评预约，座位有限！",
    description_en: "Omakase-counter sushi where you order à la carte — skip the set menu and just pick what you want, everything is supremely fresh! 火龙果's top pick: beats many ¥1000+/head places on both quality and value. Counter-only seating means groups of 4+ can't really talk to each other — keep it to 2–3. Dianping reservation required, seats are limited!",
    mustTry: ["各类海胆", "枪鱿鱼", "金枪鱼", "枪鱿鱼海胆寿司（火龙果挚爱）"],
    mustTry_en: ["Sea Urchin (all kinds)", "Squid (枪鱿鱼)", "Tuna (金枪鱼)", "Squid & Uni Sushi — 火龙果's #1 pick"],
    perPerson: "人均 ¥500–800（不含酒）",
    perPerson_en: "~¥500–800 / person (excl. drinks)",
    reservation: "必须提前大众点评预约，座位非常有限",
    reservation_en: "Dianping reservation required — very limited seats",
    groupSize: ["2–6人"],
    occasion: ["朋友聚餐", "可以请客"],
    atmosphere: ["安静"],
    rating: 3,
    spicy: 0,
    dianpingLinks: [
      { url: "https://m.dianping.com/shopinfo/H6eZ5FrwWLTUiAuN", label: "大众点评（世纪公园店）", label_en: "Dianping (Century Park)" },
      { url: "https://m.dianping.com/shopinfo/EfZkOREhKpnzycXo", label: "大众点评（前滩店）", label_en: "Dianping (Qiantan)" },
    ],
  },
  {
    name: "鲍师傅象山海鲜",
    name_en: "Bào Shīfu Xiangshan Seafood",
    category: "jiangzhe",
    category_en: "jiangzhe",
    neighborhood: "浦东 · 三林",
    neighborhood_en: "Pudong · Sanlin",
    address: "浦东·三林",
    address_en: "Pudong · Sanlin",
    description: "藏在三林街区的江浙小海鲜馆，食材新鲜，海鲜均按时令定价，价格实惠。其他海鲜也很新鲜，基本不踩雷。大厅环境正常但偏嘈杂，适合不在乎氛围的聚餐；包间有大有小（最小6人），适合谈事情或正式请客，可提前预定。",
    description_en: "A neighbourhood Jiangzhe seafood spot tucked in Sanlin, Pudong. Fresh produce, seasonal pricing on seafood, and good value overall. The rest of the menu is reliably fresh — hard to go wrong. The main hall is lively (read: noisy) — fine for casual gatherings. Private rooms range from 6-person to larger, great for business meals or hosting. Reservations available.",
    mustTry: ["家烧海鲜（精品杂鱼）", "竹蛏王", "炒海瓜子", "海鲜炒米粉（细粉·锅气足）", "丝瓜炒蛋"],
    mustTry_en: ["House-braised Mixed Seafood (家烧海鲜)", "King Razor Clams (竹蛏王)", "Stir-fried Cockles (炒海瓜子)", "Seafood Fried Rice Noodles — thin, great wok-breath (海鲜炒米粉)", "Loofah & Egg Stir-fry (丝瓜炒蛋)"],
    perPerson: "人均 ¥100–200（海鲜时令价）",
    perPerson_en: "~¥100–200 / person (seafood at market price)",
    reservation: "可预定，有大包间及6人小包间",
    reservation_en: "Reservations available; large and 6-person private rooms on offer",
    groupSize: ["2–6人", "6人以上", "有包间"],
    occasion: ["朋友聚餐", "可以请客"],
    atmosphere: ["热闹"],
    rating: 2,
    spicy: 0,
    dianping: "https://m.dianping.com/shopinfo/G81JLbccePjueIBf",
  },
  {
    name: "佬太公海鸭汤",
    name_en: "Lǎo Tài Gōng Sea Duck Soup",
    category: "jiangzhe",
    category_en: "jiangzhe",
    neighborhood: "打浦桥 / 静安（两家均可）",
    neighborhood_en: "Dapuqiao / Jing'an (both branches)",
    address: "黄浦·打浦桥 / 静安·南京西路",
    address_en: "Huangpu · Dapuqiao / Jing'an · Nanjing West Rd",
    description: "以海鸭汤起家的江浙大排档，招牌是海鸭汤和油浸带鱼，其他海鲜也很新鲜，基本不踩雷。大厅环境正常但偏嘈杂，有大小包间可预约，适合不同规模聚餐。",
    description_en: "A Jiangzhe-style seafood canteen built around its signature sea duck soup and oil-poached hairtail. The rest of the seafood menu is reliably fresh — hard to go wrong. Main hall is lively and noisy; private rooms (small 6-person and large) available for quieter gatherings.",
    mustTry: ["油浸带鱼", "海鸭汤", "海肠捞饭", "油渣芋艿"],
    mustTry_en: ["Oil-poached Hairtail (油浸带鱼)", "Sea Duck Soup (海鸭汤)", "Sea Intestine Rice (海肠捞饭)", "Taro with Pork Crackling (油渣芋艿)"],
    perPerson: "人均 ¥100–200（海鲜时令价）",
    perPerson_en: "~¥100–200 / person (seafood at market price)",
    reservation: "可预定，有大包间及6人小包间",
    reservation_en: "Reservations available; large and 6-person private rooms on offer",
    groupSize: ["2–6人", "6人以上", "有包间"],
    occasion: ["朋友聚餐", "可以请客"],
    atmosphere: ["热闹"],
    rating: 2,
    spicy: 0,
    dianpingLinks: [
      { url: "https://m.dianping.com/shopinfo/H2Qc7kqTAylKpME3", label: "大众点评（上海总店）", label_en: "Dianping (Main Branch)" },
      { url: "https://m.dianping.com/shopinfo/G1G5xawoE0aa3nVB", label: "大众点评（静安店）", label_en: "Dianping (Jing'an)" },
    ],
  },
  {
    name: "家康居酒屋",
    name_en: "Jiakang Izakaya",
    category: "japanese",
    category_en: "japanese",
    neighborhood: "全市多家分店",
    neighborhood_en: "Multiple locations across Shanghai",
    address: "全市多区",
    address_en: "Multiple locations citywide",
    description: "平价日式居酒屋，招牌蘸面是来了必点的东西——面条极度劲道，蘸汁浓郁醇厚，满足感拉满。座位偏小，氛围热闹，没有包间。一个人来饱腹一顿或者朋友小聚都很合适，不适合请客或家庭聚餐。千万千万千万记得提前大众点评预约，不约大概率吃不上！",
    description_en: "A budget-friendly izakaya, best known for its tsukemen (dipping ramen) — springy noodles with a rich, deeply flavoured broth. Small seats, lively vibe, no private rooms. Perfect solo or for a casual friends hangout; not for hosting or family dinners. MUST reserve on Dianping in advance — walk-ins almost never get in!",
    mustTry: ["蘸面（面劲道，汤汁浓郁）"],
    mustTry_en: ["Tsukemen / Dipping Ramen — springy noodles, rich broth (蘸面)"],
    perPerson: "人均 ¥100–150",
    perPerson_en: "~¥100–150 / person",
    reservation: "必须提前大众点评预约，不约大概率没位",
    reservation_en: "Dianping reservation essential — walk-ins almost always turned away",
    groupSize: ["一人可行", "2–6人"],
    occasion: ["朋友聚餐"],
    atmosphere: ["热闹"],
    rating: 1,
    spicy: 0,
    dianping: "https://m.dianping.com/shopinfo/G2xiNKXTFw23ZOta",
  },
  {
    name: "贰粉之壹·宁波海鲜米粉",
    name_en: "Èr Fěn Zhī Yī · Ningbo Seafood Rice Noodles",
    category: "jiangzhe",
    category_en: "jiangzhe",
    neighborhood: "徐汇·交通大学",
    neighborhood_en: "Xuhui · Jiaotong University",
    address: "徐汇·交通大学",
    address_en: "Xuhui · Jiaotong University",
    description: "宁波风味海鲜米粉小馆，火龙果强烈推荐炒粉——烤虾炒粉用的是细粉，锅气非常足，香！汤粉也很鲜美，不过炒粉才是灵魂。就是小面馆的环境，简单实惠，一个人来饱腹一顿最合适，价格非常亲民，还可以外卖。",
    description_en: "A Ningbo-style seafood rice noodle shop. 火龙果 strongly recommends the stir-fried version — grilled prawn fried noodles with thin rice noodles and serious wok breath. The soup noodles are also fresh and tasty, but the fried is the star. Simple canteen vibes, great value, delivery available too.",
    mustTry: ["烤虾炒粉（细粉·锅气十足）"],
    mustTry_en: ["Grilled Prawn Fried Rice Noodles — thin noodles, incredible wok breath (烤虾炒粉)"],
    perPerson: "人均 ¥30–50，可外卖",
    perPerson_en: "~¥30–50 / person · delivery available",
    groupSize: ["一人可行", "2–6人"],
    occasion: ["朋友聚餐"],
    atmosphere: ["简单"],
    rating: 1,
    spicy: 0,
    dianping: "https://m.dianping.com/shopinfo/H5uK2LHMnmh9Dt0k",
  },
  {
    name: "甬府尊鲜",
    name_en: "Yǒng Fǔ Zūn Xiān",
    category: "jiangzhe",
    category_en: "jiangzhe",
    neighborhood: "陆家嘴 / 前滩（两家均可）",
    neighborhood_en: "Lujiazui / Qiantan (both branches)",
    address: "浦东·陆家嘴 / 前滩",
    address_en: "Pudong · Lujiazui / Qiantan",
    description: "注意是甬府「尊鲜」，不是小鲜。高端浙菜馆，环境精致，适合请客。火龙果每次都专程来吃花雕鸡和沙蒜豆面——这两道必点，其他海鲜价格偏贵且不算特别出彩，可选择性点。可订位，有包间。",
    description_en: "Note: this is 尊鲜 (Zūn Xiān), not 小鲜. An upscale Zhejiang restaurant, great for hosting. 火龙果comes specifically for the Shaoxing wine chicken and sand garlic bean noodles — these two are unmissable. The rest of the seafood menu is pricey and unremarkable by comparison, order selectively. Reservations and private rooms available.",
    mustTry: ["花雕鸡（软烂入味）", "沙蒜豆面（鲜糯入味）"],
    mustTry_en: ["Shaoxing Wine Chicken — tender, deeply flavoured (花雕鸡)", "Sand Garlic Bean Noodles — fresh, sticky, full of flavour (沙蒜豆面)"],
    perPerson: "人均 ¥200–300（海鲜时令价）",
    perPerson_en: "~¥200–300 / person (seafood at market price)",
    reservation: "可订位，有包间",
    reservation_en: "Reservations available; private rooms on offer",
    groupSize: ["2–6人", "6人以上", "有包间"],
    occasion: ["可以请客"],
    atmosphere: ["精致"],
    rating: 1,
    spicy: 0,
    dianpingLinks: [
      { url: "https://m.dianping.com/shopinfo/G3HVGusYW92ygHcK", label: "大众点评（国金中心店）", label_en: "Dianping (IFC Mall)" },
      { url: "https://m.dianping.com/shopinfo/jBvgUk3qXeiBdt7w", label: "大众点评（前滩太古里店）", label_en: "Dianping (Qiantan Taikoo Li)" },
    ],
  },
  {
    name: "台州老六海鲜面馆",
    name_en: "Taizhou Lao Liu Seafood Noodles",
    category: "jiangzhe",
    category_en: "jiangzhe",
    neighborhood: "浦东·三林 / 世纪大道",
    neighborhood_en: "Pudong · Sanlin / Century Ave",
    address: "浦东·三林 / 世纪大道",
    address_en: "Pudong · Sanlin / Century Ave",
    description: "台州家烧风味的海鲜面馆，招牌小网海鲜面里有一整只梭子蟹和一整条小黄鱼，加上蛏子、花甲、虾、年糕、青菜，鲜掉眉毛！人多可点至尊海鲜拼盘，应有尽有。小面馆环境，价格非常亲民。⚠️ 强烈不建议外卖，外卖分量比堂食少很多，而且海鲜放一会儿口感大打折扣，一定要堂食！",
    description_en: "Taizhou-style braised seafood noodle shop. The signature 'small net' seafood noodles come loaded — a whole swimming crab, a whole yellow croaker, razor clams, cockles, prawns, rice cakes and greens. Insanely fresh. For groups, the deluxe seafood platter has everything. Great value, casual setting. ⚠️ Strongly avoid delivery — portions are smaller and seafood loses its magic fast. Dine in only!",
    mustTry: ["招牌小网海鲜面（一整只梭子蟹+黄鱼）", "海鲜炒年糕", "大黄鱼海鲜面", "至尊海鲜拼盘（人多时）"],
    mustTry_en: ["Signature Seafood Noodles — whole crab + yellow croaker (招牌小网海鲜面)", "Seafood Fried Rice Cakes (海鲜炒年糕)", "Yellow Croaker Seafood Noodles (大黄鱼海鲜面)", "Deluxe Seafood Platter for groups (至尊海鲜拼盘)"],
    perPerson: "人均 ¥50",
    perPerson_en: "~¥50 / person",
    groupSize: ["一人可行", "2–6人"],
    occasion: ["朋友聚餐"],
    atmosphere: ["简单", "热闹"],
    rating: 2,
    spicy: 0,
    dianpingLinks: [
      { url: "https://m.dianping.com/shopinfo/H3ZesXqC88tD6rQ4", label: "大众点评（上南总店）", label_en: "Dianping (Shangnan Main Branch)" },
      { url: "https://m.dianping.com/shopinfo/k86yv3h71DRoLyph", label: "大众点评（世纪汇店）", label_en: "Dianping (Century Link)" },
    ],
  },
  {
    name: "台乡缘（世博中心店）",
    name_en: "Táixiāngyuán (World Expo branch)",
    category: "jiangzhe",
    category_en: "jiangzhe",
    neighborhood: "浦东·世博园",
    neighborhood_en: "Pudong · World Expo",
    address: "浦东·世博园",
    address_en: "Pudong · World Expo Park",
    description: "认准世博中心店，其他店不行。台州菜代表，海鲜新鲜，家烧风味最大程度展示食材本味。环境高雅，非常适合请客，也适合朋友聚餐。6人以上可以订包间，有低消但不离谱（也可以据理力争，火龙果干成功过）。相对于台州菜天花板新荣记，性价比更高。需要销售联系方式可以找火龙果本人。避雷菜：墨鱼肠鱼饼。",
    description_en: "World Expo branch only — the other locations don't compare. The benchmark for Taizhou cuisine in Shanghai. Impeccably fresh seafood, home-style braising that lets the ingredients shine. Elegant setting, perfect for hosting. Private rooms for 6+ with a reasonable minimum spend (negotiable — 火龙果 has successfully talked them down). Better value than the revered Xin Rong Ji. Contact 火龙果 directly for the sales rep. Avoid: squid intestine fish cake (墨鱼肠鱼饼).",
    mustTry: ["各类家烧海鲜", "石锅芋艿（软糯入味！）", "沙蒜豆面", "盐卤手撕豆腐"],
    mustTry_en: ["House-braised Seasonal Seafood", "Stone Pot Taro — impossibly silky (石锅芋艿)", "Sand Garlic Bean Noodles (沙蒜豆面)", "Salt-brined Hand-torn Tofu (盐卤手撕豆腐)"],
    perPerson: "人均 ¥200–300（海鲜时令价）",
    perPerson_en: "~¥200–300 / person (seafood at market price)",
    reservation: "可订位，6人以上可订包间（有低消）",
    reservation_en: "Reservations available; private rooms for 6+ with minimum spend",
    groupSize: ["2–6人", "6人以上", "有包间"],
    occasion: ["朋友聚餐", "可以请客"],
    atmosphere: ["精致"],
    rating: 2,
    spicy: 0,
    dianping: "https://m.dianping.com/shopinfo/G3ytXFWEuiVIwkRh",
  },
  {
    name: "老兴鲜（黄浦店）",
    name_en: "Lǎo Xīng Xiān (Huangpu)",
    category: "jiangzhe",
    category_en: "jiangzhe",
    neighborhood: "黄浦·淮海路",
    neighborhood_en: "Huangpu · Huaihai Rd",
    address: "黄浦·淮海路",
    address_en: "Huangpu · Huaihai Rd",
    description: "火龙果唯一推荐的上海本帮菜！黑珍珠认证，本帮菜与江浙小海鲜双线出品，食材极度新鲜，出品极其稳定，名不虚传。必须提前预订。",
    description_en: "火龙果's one and only recommended Shanghai cuisine restaurant — Black Pearl certified. Covers both 本帮菜 and Jiangzhe seafood with exceptional consistency. Ingredients are impeccably fresh. Advance reservation required.",
    mustTry: ["白烧鳝背", "老兴鲜全家福", "鲜虾春卷", "清炒河虾仁", "酒香草头"],
    mustTry_en: ["White-braised Eel Back (白烧鳝背)", "Lao Xing Xian Seafood Platter (老兴鲜全家福)", "Fresh Prawn Spring Rolls (鲜虾春卷)", "Stir-fried River Shrimp (清炒河虾仁)", "Wine-fragrant Clover (酒香草头)"],
    perPerson: "人均 ¥250–350",
    perPerson_en: "~¥250–350 / person",
    reservation: "必须提前预订",
    reservation_en: "Advance reservation required",
    groupSize: ["2–6人", "6人以上", "有包间"],
    occasion: ["朋友聚餐", "可以请客"],
    atmosphere: ["精致", "安静"],
    rating: 1,
    spicy: 0,
    dianping: "https://m.dianping.com/shopinfo/H7vprrMRBaF2iOCZ",
  },
  {
    name: "美醉煨汤",
    category: "jiangzhe",
    address: "黄浦·大沽路",
    description: "环境很舒服的小店，基本都是江浙经典海鲜烧法，食材新鲜且出品稳定，可以放心点菜，但说不上特别惊艳，推荐的点主要在菜水平不错+氛围很好，很适合几个姐妹吃吃饭聊聊天，还有个小院子，春夏之交坐在院子里非常舒适。",
    mustTry: ["墨鱼排骨汤", "家烧台州红虾", "家烧蛏子"],
    perPerson: "人均 ¥200–300（海鲜时令价）",
    groupSize: ["2–6人"],
    occasion: ["朋友聚餐"],
    atmosphere: ["精致", "安静"],
    rating: 1,
    dianping: "https://m.dianping.com/shopinfo/HaDjlf30WUZ4zxJj",
  },
  {
    name: "威皇广福和小海鲜",
    category: "domestic",
    address: "全市多家分店",
    description: "花雕醉鸡煲的鲜美这么多年都出品稳定，是冬天隔段时间就会想喝的！推荐顺序：先喝鸡汤，再下海鲜，最后下牛肉！不可预定，饭点排队，建议错峰前往。",
    mustTry: ["花雕醉鸡煲", "煲仔饭"],
    perPerson: "人均 ¥100",
    reservation: "不可预定，饭点排队，建议错峰前往",
    groupSize: ["2–6人"],
    occasion: ["朋友聚餐"],
    atmosphere: ["热闹", "简单"],
    rating: 1,
    dianpingLinks: [
      { url: "https://m.dianping.com/shopinfo/l1HFMJvA6u6HXcya", label: "大众点评（襄阳南路店）" },
      { url: "https://m.dianping.com/shopinfo/l9dBzhcgS9NHAckz", label: "大众点评（乌鲁木齐南路店）" },
      { url: "https://m.dianping.com/shopinfo/laLQpd0xqQP9ZgCQ", label: "大众点评（嘉善路店）" },
    ],
  },
  {
    name: "旧村·砂锅焗海鲜",
    category: "jiangzhe",
    address: "全市多家分店",
    description: "世界上最好吃的鸦片鱼头！黄油的香气和鸦片鱼头的鲜味被砂锅完美地融合并包裹，火龙果一人每次可吃掉一大份！皮皮虾和梭子蟹季节推荐干焗，虾肉和蟹肉的鲜美都透着黄油奶香味。猪蹄鸡爪炖得非常软烂，入口即化。唯一缺点：吃多了有点咸，口淡的朋友慎入。不可预定，饭点排队，建议错峰前往。",
    mustTry: ["鸦片鱼头", "干焗皮皮虾", "干焗梭子蟹", "猪蹄鸡爪煲"],
    perPerson: "人均 ¥100–150（海鲜时令价）",
    reservation: "不可预定，饭点排队，建议错峰前往",
    groupSize: ["2–6人"],
    occasion: ["朋友聚餐"],
    atmosphere: ["热闹", "简单"],
    rating: 1,
    dianpingLinks: [
      { url: "https://m.dianping.com/shopinfo/l4RK3z1HcJzRuL0G", label: "大众点评（世纪汇店）" },
      { url: "https://m.dianping.com/shopinfo/l7x4O7o1ocBfSPLn", label: "大众点评（合生汇店）" },
    ],
  },
  {
    name: "地球美食剧场",
    category: "japanese",
    address: "长宁·番禺路",
    description: "仪式感拉满的纪念日/生日推荐，食材根据季节变化，新鲜度和出品都令人安心。大屏幕随季节和食材变化，从日出后的潺潺流水到夜幕后的璀璨烟花，视觉和味觉都很享受的两个小时。最后会一起动手做可爱的小纪念品（比如一小瓶柚子酒），大屏幕上还有庆祝画面。花下去的钱从各方面来说都得到了满意的体验。",
    mustTry: ["随季节时令套餐"],
    perPerson: "人均 ¥1000",
    reservation: "提前预定",
    groupSize: ["2–6人"],
    occasion: ["可以请客"],
    atmosphere: ["精致", "安静"],
    rating: 1,
    dianping: "https://m.dianping.com/shopinfo/k8ZlQIWaZmVOAxSP",
  },
  {
    name: "ATELIER IZAKAYA",
    category: "japanese",
    address: "全市两家分店",
    description: "好吃的漂亮饭，环境属于经典精致bistro，烧鸟味道都不错，下酒菜偏多，适合生日或者三五好友聚聚。都是长桌子，人多了会有坐得太散听不到讲话的问题。烧鸟都是单点，丰俭由人。要预定。",
    mustTry: ["紫苏鸡腿肉", "牛肋条", "鸡肉丸子"],
    perPerson: "人均 ¥250–500",
    reservation: "要预定",
    groupSize: ["2–6人"],
    occasion: ["朋友聚餐"],
    atmosphere: ["热闹", "精致"],
    rating: 1,
    dianpingLinks: [
      { url: "https://m.dianping.com/shopinfo/G58m51Vc4ikIL0Lv", label: "大众点评（外滩店）" },
      { url: "https://m.dianping.com/shopinfo/H2NnweVAEb4mQOZP", label: "大众点评（南京西路店）" },
    ],
  },
  {
    name: "佬表炒菜猛",
    category: "jiangxi",
    address: "浦东·蓝村路",
    description: "南昌人推荐唯一南昌爆炒店，锅气正确，无须其他语言赘述！大厅适合2-4人，有大包间。平常不太排队，但饭点可以预定一下比较保险，可以点外卖，美味不减。",
    mustTry: ["辣炒鲜吊龙", "干锅有机芦笋干（贡菜干）", "火爆片片毛肚", "辣鸡爪", "招牌热辣小炒鸡", "绝杀莲花血鸭"],
    perPerson: "人均 ¥100",
    groupSize: ["2–6人", "6人以上", "有包间"],
    occasion: ["朋友聚餐"],
    atmosphere: ["热闹", "简单"],
    rating: 3,
    spicy: 5,
    dianping: "https://m.dianping.com/shopinfo/G6d756SR6pbjVvZH",
  },
  {
    name: "悦江瓷耕颂",
    category: "jiangxi",
    address: "浦东·前滩（陆家嘴广场）",
    description: "环境精致且味道正宗的江西菜，非常适合请客，尤其是作为江西人带大家吃吃江西菜，很好的体验。萍乡血鸭做的非常正宗，其中一果就是专门给到这道菜，馋的时候自己也会去吃一份，从头辣到脚！",
    mustTry: ["莲花血鸭", "辣椒炒肉", "老南昌藕片", "黄豆焖凤爪"],
    perPerson: "人均 ¥150–200",
    reservation: "建议提前预定",
    groupSize: ["2–6人", "6人以上", "有包间"],
    occasion: ["朋友聚餐", "可以请客"],
    atmosphere: ["安静", "精致"],
    rating: 2,
    spicy: 5,
    dianping: "https://m.dianping.com/shopinfo/GaFm6NmnoqHr0DFb",
  },
  {
    name: "江西小炒",
    category: "jiangxi",
    address: "浦东·世纪公园",
    description: "路边摊的环境，只推荐南昌拌粉这一道菜，非常正宗，就是南昌街边早餐店的味道。",
    mustTry: ["南昌拌粉"],
    perPerson: "人均 ¥20",
    groupSize: ["一人可行", "2–6人"],
    occasion: [],
    atmosphere: ["简单"],
    rating: 1,
    spicy: 5,
    dianping: "https://m.dianping.com/shopinfo/G2ye4Ox8VD8YeNBm",
  },
  {
    name: "南门口",
    category: "yunguizhou",
    address: "前滩 / 五角场",
    description: "无敌正宗的贵阳豆米火锅和铁签小串，环境简单，适合朋友聚餐，也适合自己馋的时候去撸串，太爽了！饭点要排队，大桌可以电话预定，小桌建议错峰前往。",
    mustTry: ["豆米火锅（搭配软哨·猪肉丸子）", "烤小肠", "烤小瓜", "洋芋粑"],
    perPerson: "人均 ¥74–90",
    reservation: "大桌可电话预定，小桌建议错峰前往",
    groupSize: ["一人可行", "2–6人"],
    occasion: ["朋友聚餐"],
    atmosphere: ["简单", "热闹"],
    rating: 3,
    spicy: 3,
    dianpingLinks: [
      { url: "https://m.dianping.com/shopinfo/l4pzEhmtn365ESoI", label: "大众点评（前滩店）" },
      { url: "https://m.dianping.com/shopinfo/H1wcm6q8rxvCEuMX", label: "大众点评（五角场店）" },
    ],
  },
  {
    name: "安徽省驻沪办招待所",
    category: "domestic",
    address: "长宁·新华路（上海影城）",
    description: "在小洋楼里的精致安徽菜，只有包间，需提前预约，非常非常适合请客。午餐是点单，晚餐是配餐形式，服务到位。最最最最好吃的是蒙城烧饼，千层起酥，一口咬下去酥脆里带着油脂的味道，太满足了！非常期待他们开一个专卖蒙城烧饼的窗口，这样的话我每天都要去报道。",
    mustTry: ["蒙城烧饼", "臭豆腐烧肥肠"],
    perPerson: "人均 ¥300–500",
    reservation: "需提前预约",
    groupSize: ["2–6人", "6人以上", "有包间"],
    occasion: ["可以请客"],
    atmosphere: ["精致", "安静"],
    rating: 1,
    dianping: "https://m.dianping.com/shopinfo/l4LYDF2CNtELxdb6",
  },
  {
    name: "衢宴·钱江源",
    category: "domestic",
    address: "浦东·陆家嘴",
    description: "正宗衢州菜，辣辣的非常过瘾，有季节鲜菜，包间居多，大的小的都有，3–4人也是坐包间，需要预定。",
    mustTry: ["衢州三宝", "特色炒排骨", "开化小杂鱼/清水鱼", "小炒黄牛肉", "青番茄火腿肉"],
    perPerson: "人均 ¥128",
    reservation: "需要预定",
    groupSize: ["2–6人", "6人以上", "有包间"],
    occasion: ["朋友聚餐", "可以请客"],
    atmosphere: ["热闹"],
    rating: 2,
    spicy: 3,
    dianping: "https://m.dianping.com/shopinfo/H1HJSqLzC3PorX3F",
  },
  {
    name: "BLAZ",
    category: "international",
    address: "徐汇·东湖路",
    description: "适合过生日/纪念日的精致bistro，菜品经常更新，常去常新，出品质量稳定，环境氛围很chill，还有个小院子，春夏之际坐在院子里喝酒聊天很舒服。需要预定。",
    mustTry: ["（菜单随季节更新，任意点都值得）"],
    perPerson: "人均 ¥500",
    reservation: "需要预定",
    groupSize: ["2–6人"],
    occasion: ["朋友聚餐", "可以请客"],
    atmosphere: ["精致", "热闹"],
    rating: 1,
    dianping: "https://m.dianping.com/shopinfo/G2vTMCZaiLPgaDkA",
  },
  {
    name: "川为食族",
    category: "sichuan",
    address: "浦东·三林（板泉路）",
    description: "路边小店，现炒现吃，锅气很足。有大圆桌最多可以坐8个人左右，不论大桌小桌都需要提前电话/微信预定，错峰前往可行，芋儿鸡非常非常好吃也要提前预定，都是经典川菜，点自己喜欢的就行，不踩雷。",
    mustTry: ["芋儿鸡", "馋嘴牛蛙", "火爆肥肠", "火爆黄喉", "火爆腰花", "回锅肉"],
    perPerson: "人均 ¥108",
    reservation: "需提前电话/微信预定",
    groupSize: ["2–6人", "6人以上"],
    occasion: ["朋友聚餐"],
    atmosphere: ["简单", "热闹"],
    rating: 2,
    spicy: 3,
    dianping: "https://m.dianping.com/shopinfo/G58A23giQl3RHsWy",
  },
  {
    name: "O'mills Sourdough",
    category: "bakery",
    address: "全市多家分店",
    description: "二颗火龙果全部给到鳗鱼pizza！！！饼皮烤得恰到好处的有些韧性，鳗鱼鲜美配上紫苏梅子等佐料，融合得超级无敌好，属于经常会突然想吃的食物！也适合在天气好和姐妹约一个精致的brunch。不能预定，饭点需要等位，尤其是周末天气好的上午，早点去比较好。",
    mustTry: ["鳗鱼pizza"],
    perPerson: "人均 ¥134–142",
    reservation: "不能预定，饭点需要等位，建议错峰前往",
    groupSize: ["2–6人"],
    occasion: ["朋友聚餐"],
    atmosphere: ["精致", "热闹"],
    rating: 2,
    dianpingLinks: [
      { url: "https://m.dianping.com/shopinfo/G4tlNT8Qpw9ErRnK", label: "大众点评（永嘉路店）" },
      { url: "https://m.dianping.com/shopinfo/G9zkjRVOqU7NQ2zg", label: "大众点评（浦东嘉里城店）" },
    ],
  },

  // ── 川菜 ──
  {
    name: "对酒当歌",
    category: "sichuan",
    address: "全市多家分店",
    description: "一家出品正常的川菜店，可以点外卖，推荐完全是因为「武林麻辣鸭头」这道菜，酥酥脆脆，香辣中带一点点麻，吃完嘴里不会感觉超咸，吃了不下几十次！外卖可以点半份，非常贴心。",
    mustTry: ["武林麻辣鸭头"],
    perPerson: "人均 ¥50–100",
    groupSize: ["一人可行", "2–6人", "6人以上", "有包间"],
    occasion: ["朋友聚餐"],
    atmosphere: ["简单", "热闹"],
    rating: 1,
    spicy: 2,
    dianpingLinks: [
      { url: "https://m.dianping.com/shopinfo/H1dkg8xxxlFpuANX", label: "大众点评（八佰伴店）" },
      { url: "https://m.dianping.com/shopinfo/G6F7rMVAvEY3rE5w", label: "大众点评（陆家浜路店）" },
    ],
  },
  {
    name: "老吴家川菜",
    category: "sichuan",
    address: "长宁·中山公园（昭化路）",
    description: "川菜苍蝇馆子，出品稳定，没有踩雷的，想吃啥点啥，想吃辣的时候去总是不会出错的选择，会得到很满足的体验。饭点可能排队，可以错峰前往。",
    mustTry: ["麻婆豆腐", "蒜泥白肉", "夫妻肺片", "辣子鸡", "水煮牛肉", "爆炒肥肠"],
    perPerson: "人均 ¥97",
    reservation: "饭点可能排队，可以错峰前往",
    groupSize: ["2–6人"],
    occasion: ["朋友聚餐"],
    atmosphere: ["简单", "热闹"],
    rating: 1,
    spicy: 3,
    dianping: "https://m.dianping.com/shopinfo/H6QCRHKbWAJJ8X0B",
  },

  // ── 湘菜 ──
  {
    name: "御鲤湘",
    category: "hunan",
    address: "全市多家分店",
    description: "地道且全面的湘菜馆子，出品稳定，没有踩雷的，想吃辣的时候去总是不会出错的选择，会得到很满足的体验。地理位置很方便，饭点可能排队，包间需要提前预定。",
    mustTry: ["小炒黄牛肉", "双色鱼头", "孜然排骨", "脆皮猪手", "鱼籽鱼泡"],
    perPerson: "人均 ¥100",
    reservation: "饭点可能排队，包间建议提前预定",
    groupSize: ["2–6人", "6人以上", "有包间"],
    occasion: ["朋友聚餐"],
    atmosphere: ["简单", "热闹"],
    rating: 1,
    spicy: 3,
    dianpingLinks: [
      { url: "https://m.dianping.com/shopinfo/k5BVerMb2eAtrcYm", label: "大众点评（淮海中路店）" },
      { url: "https://m.dianping.com/shopinfo/k4DVUYUuEbnWoDlb", label: "大众点评（北京西路店）" },
      { url: "https://m.dianping.com/shopinfo/H8x1GQKdqitXhhcX", label: "大众点评（马当路店）" },
    ],
  },
  {
    name: "十里湘荟",
    category: "hunan",
    address: "浦东·前滩太古里",
    description: "唯一推荐的环境和口味均在线的湘菜馆，毕竟好吃的湘菜馆基本都是苍蝇馆子。其中一果必须给到「菌皇汁纯手工黑豆腐」——黑豆腐表皮煎到有点点酥之后下入浓汤炖煮，收汁后一口下去，豆腐的滑嫩+豆皮的酥软+酱汁的鲜美集中爆发，美滋滋！大厅适合2-6人小桌，包间适合请客和过生日等活动。",
    mustTry: ["菌皇汁纯手工黑豆腐", "黑金鸡爪", "干锅花生苗", "脆皮发财猪手", "小炒黄牛肉", "剁椒鱼头", "紫苏跳跳蛙"],
    perPerson: "人均 ¥150–200",
    groupSize: ["2–6人", "6人以上", "有包间"],
    occasion: ["朋友聚餐", "可以请客"],
    atmosphere: ["精致", "热闹"],
    rating: 2,
    spicy: 3,
    dianping: "https://m.dianping.com/shopinfo/Gaxiq2S0hnYVtneS",
  },
  {
    name: "久久滴水洞",
    category: "hunan",
    address: "黄浦·淮海路（茂名南路）",
    description: "地道且全面的湘菜馆子，出品稳定，没有踩雷的，想吃辣的时候随时去都不出错。一果给味道，一果给地理位置绝佳且基本不需要排队，随时想吃随时吃得到。门头较小不好找，大厅小桌子适合2-4人。",
    mustTry: ["小炒牛肉", "孜然排骨", "爆炒猪脚皮"],
    perPerson: "人均 ¥100–150",
    reservation: "包间可能需要预定",
    groupSize: ["2–6人", "6人以上", "有包间"],
    occasion: ["朋友聚餐"],
    atmosphere: ["简单", "热闹"],
    rating: 2,
    spicy: 3,
    dianping: "https://m.dianping.com/shopinfo/l3ad1TqRQajgoIzQ",
  },

  // ── 国内其他 ──
  {
    name: "柿合缘新京菜",
    category: "domestic",
    address: "陆家嘴 / 静安嘉里",
    description: "虽然北京菜实在没什么值得一说的，但这家的鱼头泡油条真的值得一来再来！浓郁香醇的绝味鱼头，汤汁浓郁鲜美，大油条剪小后吸满汤汁，咬下去超满足！整体味道很不错，但点菜有技巧：绝不要点烤鸭，也不要点精致贵菜（鹅肝、牛小排等），选接地气的菜反而都很好吃。",
    mustTry: ["段式绝味鱼头（加油条）", "老北京爆肚", "黑叉烧", "炸酱面"],
    perPerson: "人均 ¥150–200",
    groupSize: ["2–6人", "6人以上", "有包间"],
    occasion: ["朋友聚餐", "可以请客"],
    atmosphere: ["精致", "热闹"],
    rating: 1,
    dianpingLinks: [
      { url: "https://m.dianping.com/shopinfo/l58ZDt6lr4cWvIXW", label: "大众点评（国金中心店）" },
      { url: "https://m.dianping.com/shopinfo/k55QG3tVyEnxn0O7", label: "大众点评（静安嘉里中心店）" },
    ],
  },
  {
    name: "青年公社烤鸭",
    category: "domestic",
    address: "全市多家分店",
    description: "吃烤鸭唯一指定店，只要想吃烤鸭就会直接来，其他菜也可圈可点，芝士酥皮大虾也是常吃常新，来过非常非常多次。大厅适合2-6人，有小圆桌，包间有4-6人小包间也有10人大包间，可以请客、过生日等活动。",
    mustTry: ["桂花香酥烤鸭（鸭架建议椒盐）", "芝士酥皮虾", "浓汤老豆腐", "砂锅肉炒扁豆", "老北京糖油饼", "炙子羊肉"],
    perPerson: "人均 ¥100–150",
    groupSize: ["2–6人", "6人以上", "有包间"],
    occasion: ["朋友聚餐", "可以请客"],
    atmosphere: ["精致", "热闹"],
    rating: 2,
    dianpingLinks: [
      { url: "https://m.dianping.com/shopinfo/H1G8cudVxUjA52jO", label: "大众点评（正大乐城店）" },
      { url: "https://m.dianping.com/shopinfo/FUnAOyRX3AROE7PY", label: "大众点评（创智天地店）" },
      { url: "https://m.dianping.com/shopinfo/H7l0Q7gUZ9IxL7mN", label: "大众点评（华润时代广场店）" },
    ],
  },
  {
    name: "吉友粥底火锅",
    category: "domestic",
    address: "黄浦·新天地",
    description: "xuān掉眉毛的粥底海鲜火锅！海鲜随便点自己想吃的即可，都很新鲜，和糯糯的白粥煮在一起，冬天温暖又满足，鲜牛肉、牛肉丸新鲜度也有保证，放心大胆点。饭点可能排队，可以预定，人多坐包间。",
    mustTry: ["竹节虾", "竹蛏王", "松叶蟹", "鲜牛展", "牛肉丸", "椒盐鸡尾虾", "炸鸡翅"],
    perPerson: "人均 ¥150–200（海鲜时令价）",
    reservation: "饭点可能排队，可以预定",
    groupSize: ["2–6人", "6人以上", "有包间"],
    occasion: ["朋友聚餐"],
    atmosphere: ["简单", "热闹"],
    rating: 2,
    dianping: "https://m.dianping.com/shopinfo/k1yOioPbyjlbkSor",
  },
  {
    name: "纯味斑鱼府",
    category: "domestic",
    address: "浦东·八佰伴",
    description: "唯一推荐鱼火锅！招牌斑鱼片薄如蝉翼，在高汤里浅浅烫几秒就卷起来，搭配海鲜酱油，xuān掉眉毛！其他海鲜新鲜度也有保证，但每次基本只吃斑鱼片，因为真的太太太好吃了，美味程度远超其他品种！",
    mustTry: ["招牌斑鱼片"],
    perPerson: "人均 ¥150–200（海鲜时令价）",
    groupSize: ["2–6人"],
    occasion: ["朋友聚餐"],
    atmosphere: ["精致"],
    rating: 1,
    dianping: "https://m.dianping.com/shopinfo/l2SurazpMbz6rs3p",
  },
  {
    name: "新光酒家·蟹宴",
    category: "domestic",
    address: "浦东·世纪公园",
    description: "吃大闸蟹唯一指定店，大闸蟹季节有专门的大闸蟹菜单（5道或7道），将大闸蟹呈现为不同形态，全面而且满足，每年大闸蟹季节必报道。注意⚠️ 世纪公园店体验更佳，不建议去黄浦店。",
    mustTry: ["时令大闸蟹套餐"],
    perPerson: "人均 ¥300–500",
    groupSize: ["2–6人", "6人以上", "有包间"],
    occasion: ["朋友聚餐", "可以请客"],
    atmosphere: ["精致"],
    rating: 2,
    dianping: "https://m.dianping.com/shopinfo/H2HpQr5KnMv3vrzG",
  },
  {
    name: "倪春龙虾",
    category: "domestic",
    address: "浦东·金杨（德平路）",
    description: "吃小龙虾唯一指定店，小龙虾个头足斤足两，各种口味做的都很到位，吃就完事了。夏天饭点可能没座儿，可以提前预定，或者错峰前往。",
    mustTry: ["十三香小龙虾", "蒜泥小龙虾", "椒盐皮皮虾"],
    perPerson: "人均 ¥150–200（小龙虾时令价）",
    reservation: "夏天饭点可能没座，可提前预定或错峰前往",
    groupSize: ["2–6人"],
    occasion: ["朋友聚餐"],
    atmosphere: ["简单", "热闹"],
    rating: 1,
    spicy: 2,
    dianping: "https://m.dianping.com/shopinfo/G3cgyuITu8HZuuCn",
  },

  // ── 国外其他 ──
  {
    name: "POETS泰狮",
    category: "international",
    address: "全市多家分店",
    description: "环境和味道都在线的泰国菜，盲点不出错，各类特色饮料（泰奶、鸡尾酒）也很好喝！两家分店均有室外座位，西岸的店有对着江的大露台，很舒服，适合小范围聚餐或请客。饭点排队，错峰前往或提前排队。",
    mustTry: ["招牌咖喱蟹", "泰式火山排骨", "冬阴功汤", "炭烤猪颈肉", "虾酱空心菜"],
    perPerson: "人均 ¥200–250",
    reservation: "饭点排队，建议错峰前往或提前排队",
    groupSize: ["2–6人"],
    occasion: ["朋友聚餐", "可以请客"],
    atmosphere: ["精致", "热闹"],
    rating: 1,
    spicy: 1,
    dianpingLinks: [
      { url: "https://m.dianping.com/shopinfo/EVoyyje4Pmm1OdiV", label: "大众点评（西岸梦中心店）" },
      { url: "https://m.dianping.com/shopinfo/k1yReFduL5Sxrv0r", label: "大众点评（滨江店）" },
    ],
  },
  {
    name: "Tapa Tapa",
    category: "international",
    address: "全市多家分店",
    description: "环境和氛围都非常nice，西岸的店有室内也有室外，天气好时对着江很舒服；富民路这家装修非常西班牙，周中某天晚上有Flamenco弗朗明戈表演（可致电确认）。Tapas选择很多，油浸虾、炖牛肚、炸鱿鱼等经典菜色品质都在线，Sangria清爽，适合朋友聚餐聊聊天。",
    mustTry: ["Sangria", "油浸虾", "炖牛肚", "炸鱿鱼", "蟹肉土豆饼"],
    perPerson: "人均 ¥200–250",
    groupSize: ["2–6人"],
    occasion: ["朋友聚餐"],
    atmosphere: ["精致", "热闹"],
    rating: 2,
    dianpingLinks: [
      { url: "https://m.dianping.com/shopinfo/k9pTMwown0SSS0HQ", label: "大众点评（富民路店）" },
      { url: "https://m.dianping.com/shopinfo/k2T24HUzdh1WAWo8", label: "大众点评（西岸梦中心店）" },
    ],
  },

  // ── 面包甜品 ──
  {
    name: "聚福",
    category: "bakery",
    address: "徐汇·衡山路（乌鲁木齐路）",
    description: "很有自己特色的蛋糕店，甜度适中，有位置点咖啡可以坐下聊天。",
    mustTry: ["血糯米千层", "咸蛋黄巴斯克", "咸蛋黄流心千层"],
    perPerson: "人均 ¥50",
    groupSize: ["一人可行", "2–6人"],
    occasion: ["朋友聚餐"],
    atmosphere: ["精致"],
    rating: 1,
    dianping: "https://m.dianping.com/shopinfo/k4T8k9apcj3rC9Yi",
  },
  {
    name: "潘甬兴糕点",
    category: "bakery",
    address: "全市多家分店",
    description: "糯叽叽的中式糕点唯一推荐品牌，都是小摊头，买完就走，没有座位。青团100分！！要吃艾草的，内馅挑自己爱吃的就行——蛋黄肉松油滋滋恰到好处，完全不腻，和艾草的清香融合得超级完美。其他糕点出品也都在平均以上，按自己喜欢点，不踩雷。",
    mustTry: ["艾草青团", "桔红糕", "酒酿桂花水塔糕", "黑米小米糕", "条头糕"],
    perPerson: "人均 ¥20–50",
    groupSize: ["一人可行", "2–6人"],
    occasion: [],
    atmosphere: ["简单"],
    rating: 3,
    dianpingLinks: [
      { url: "https://m.dianping.com/shopinfo/l1esUCXYIYixHVI2", label: "大众点评（南汇路店）" },
      { url: "https://m.dianping.com/shopinfo/k3GbKTIr6ycBIRet", label: "大众点评（瑞金二路店）" },
    ],
  },
  {
    name: "JESSY&JERRY",
    category: "bakery",
    address: "全市多家分店",
    description: "季节蛋糕王者，新鲜时令水果+动物奶油，吃过好多种都不踩雷，按照自己喜欢的水果点就行。4寸的size非常刚好，不管是小范围过生日还是自己嘴馋都很合适！可以直接店里买，也可以小程序下单去拿，店里一般有座位可以坐下聊聊天。",
    mustTry: ["（当季时令水果蛋糕，按喜好选）"],
    perPerson: "蛋糕 ¥100–200",
    groupSize: ["一人可行", "2–6人"],
    occasion: ["朋友聚餐"],
    atmosphere: ["精致"],
    rating: 2,
    dianpingLinks: [
      { url: "https://m.dianping.com/shopinfo/l4YOeq831VoAoVvr", label: "大众点评（静安嘉里中心店）" },
      { url: "https://m.dianping.com/shopinfo/G5rut4ZFKwdIiWxr", label: "大众点评（前滩太古里店）" },
      { url: "https://m.dianping.com/shopinfo/G6dz4KzWbsgOKC1R", label: "大众点评（BFC外滩金融中心店）" },
    ],
  },
  {
    name: "WenTinG文汀",
    category: "bakery",
    address: "全市多家分店",
    description: "蛋糕全肯定，最最最推荐晴王酸奶——青提的清新搭配绵密动物奶油，奶味很足，常吃常新。栗子的、草莓的、芒果的都吃过，新鲜美味保证，按照自己喜欢的选就行。4寸size非常刚好，小范围过生日或自己嘴馋都很合适！可以直接店里买，也可以小程序下单去拿，店里一般有座位。",
    mustTry: ["晴王酸奶蛋糕", "（其他时令蛋糕按喜好选）"],
    perPerson: "蛋糕 ¥100–200",
    groupSize: ["一人可行", "2–6人"],
    occasion: ["朋友聚餐"],
    atmosphere: ["精致"],
    rating: 3,
    dianpingLinks: [
      { url: "https://m.dianping.com/shopinfo/G7IBrMYcCzwK8ihl", label: "大众点评（新天地广场店）" },
      { url: "https://m.dianping.com/shopinfo/k3ue47iVnmK020Dk", label: "大众点评（前滩太古里店）" },
    ],
  },
  {
    name: "珈琲光景",
    category: "bakery",
    address: "徐汇·淮海中路（衡山路）",
    description: "挚爱咖啡馆，多年来的绝对断层第一，喝了四五年了，晴天拿铁你就喝吧，一喝一个不吱声。有零星几个小位置可以坐下聊天，但经常去的时候已经满了。",
    mustTry: ["晴天拿铁"],
    perPerson: "人均 ¥54",
    groupSize: ["一人可行", "2–6人"],
    occasion: [],
    atmosphere: ["安静", "精致"],
    rating: 3,
    dianping: "https://m.dianping.com/shopinfo/katHXbVXOnNtE8Kv",
  },

  // ── 酒吧 ──
  {
    name: "Wooden Paradise",
    category: "bar",
    address: "徐汇·长乐路",
    description: "简单舒服的木质环境，可以坐一楼吧台，也有楼上的2-4人小桌。很认真设计并制作每一款酒，有非常多自己独特的酒款，工作日有happy hour。近期挚爱是桂花汤力，会为了这一杯酒专门去，然后一晚上都喝这一款。有特调，可以和调酒师沟通。喝酒的点人多，建议预定或者早点去。",
    mustTry: ["桂花汤力"],
    perPerson: "酒 ¥60–100/杯",
    reservation: "建议预定或错峰前往",
    groupSize: ["2–6人"],
    occasion: ["朋友聚餐"],
    atmosphere: ["简单"],
    rating: 3,
    dianping: "https://m.dianping.com/shopshare/G3oZOiZU2mjmp6fo",
  },
  {
    name: "Punch Room",
    category: "bar",
    address: "黄浦·外滩（艾迪逊酒店）",
    description: "适合既想要环境也想要口味的时候，尤其适合带外地来玩的朋友前往。环境一流，在艾迪逊酒店高层，有大落地窗看黄浦江，夜景很美，窗边座位需要提前预定，很值得一去。推荐Shanghai Milk——口味非常均衡、带着淡淡奶香和果香的奶洗鸡尾酒。",
    mustTry: ["Shanghai Milk"],
    perPerson: "酒 ¥120/杯",
    reservation: "窗边座位需要提前预定",
    groupSize: ["2–6人"],
    occasion: ["朋友聚餐", "可以请客"],
    atmosphere: ["精致", "安静"],
    rating: 1,
    dianping: "https://m.dianping.com/shopshare/G2sAiG1xDMPxcgfp",
  },
  {
    name: "GOEN·缘",
    category: "bar",
    address: "（详见大众点评）",
    description: "喝了很多年的小小酒吧，老板是日本人，鸡尾酒偏日式，酒单挺有意思的，酒体轻盈，呈现有设计感，比较适合酒量不算太好的朋友们小酌聊天。有特调，可以和调酒师沟通。",
    mustTry: ["特调（询问调酒师）"],
    perPerson: "酒 ¥100/杯",
    groupSize: ["2–6人"],
    occasion: ["朋友聚餐"],
    atmosphere: ["精致", "安静"],
    rating: 1,
    dianping: "https://m.dianping.com/shopshare/H79Pc50BFTdbZN55",
  },
  {
    name: "壹个酒窖",
    category: "bar",
    address: "（详见大众点评）",
    description: "葡萄酒窖，很纯粹的选酒+喝酒的地方，老板很nice，是WSET4的老前辈了。店里不大，人也不多，随时去喝就行。基本都是开一整瓶，和朋友聊聊天，有时候店里也有附近爱喝酒的人一起聊聊天，很舒服，天气好可以坐室外。",
    mustTry: ["（按心情选酒）"],
    perPerson: "按酒定价",
    groupSize: ["2–6人"],
    occasion: ["朋友聚餐"],
    atmosphere: ["简单", "安静"],
    rating: 2,
    dianping: "https://m.dianping.com/shopshare/H4cZnBO4tuN3N6Hi",
  },
];
